### ISSUE TITLE
AttributeError: 'module' object has no attribute 'kiwisdr'

### ISSUE THREAD

**Issue by williamntv** [hcab14/gr-kiwisdr#3]
Hello, could you please help me solve this issue? I was trying to run the kiwisdr in gnuradio and encountered this error below. Not sure what to do. Thank you!

Block paths:
/usr/share/gnuradio/grc/blocks
/usr/local/share/gnuradio/grc/blocks

Loading: "/home/wntv/Desktop/test.grc"
>>> Done

Generating: '/home/wntv/Desktop/top_block.py'
>>> Warning: This flow graph contains a throttle block and another rate limiting block, e.g. a hardware source or sink. This is usually undesired. Consider removing the throttle block.

Executing: /usr/bin/python2 -u /home/wntv/Desktop/top_block.py

Traceback (most recent call last):
  File "/home/wntv/Desktop/top_block.py", line 112, in <module>
    main()
  File "/home/wntv/Desktop/top_block.py", line 100, in main
    tb = top_block_cls()
  File "/home/wntv/Desktop/top_block.py", line 69, in __init__
    self.kiwisdr_kiwisdr_0 = kiwisdr.kiwisdr('', '',14076000,0,3000)
AttributeError: 'module' object has no attribute 'kiwisdr'

>>> Done

Generating: '/home/wntv/Desktop/top_block.py'

Executing: /usr/bin/python2 -u /home/wntv/Desktop/top_block.py

Traceback (most recent call last):
  File "/home/wntv/Desktop/top_block.py", line 223, in <module>
    main()
  File "/home/wntv/Desktop/top_block.py", line 211, in main
    tb = top_block_cls()
  File "/home/wntv/Desktop/top_block.py", line 159, in __init__
    self.kiwisdr_kiwisdr_0 = kiwisdr.kiwisdr('aspliden.mooo.com', '8073',4932,-6000,6000)
AttributeError: 'module' object has no attribute 'kiwisdr'

>>> Done

Generating: '/home/wntv/Desktop/top_block.py'

Executing: /usr/bin/python2 -u /home/wntv/Desktop/top_block.py

Traceback (most recent call last):
  File "/home/wntv/Desktop/top_block.py", line 223, in <module>
    main()
  File "/home/wntv/Desktop/top_block.py", line 211, in main
    tb = top_block_cls()
  File "/home/wntv/Desktop/top_block.py", line 159, in __init__
    self.kiwisdr_kiwisdr_0 = kiwisdr.kiwisdr('my.kiwisdr.com', '8073',4932,-6000,6000)
AttributeError: 'module' object has no attribute 'kiwisdr'

>>> Done

**Comment by hcab14** [comment]
Hi @williamntv 

the relevant error message is 

> AttributeError: 'module' object has no attribute 'kiwisdr'

and it means that the kiwisdr block is not available in python, _i.e._, it has not been build.

Have you installed doxygen? If not please install it, `sudo apt install doxygen`, and then run cmake and make again in a clean build directory.

Also make sure you have swig3.0 installed (`sudo apt install swig3.0`).

**Comment by williamntv** [comment]
Thank you for your reply. Me and my lab partner, we managed to re-install all the required software packages and the block is now showing in gnuradio. However, we are now facing yet another issue. As soon as we tried to run script, it would crash to desktop right away. My lab partner found that the issue is with segmentation fault and we don't know what else to try. Maybe we will have to reinstall gnuradio and see if that will help. We are working on Seismograph project for a radio course at University of Victoria, by the way. Thank you for your support.

**Comment by hcab14** [comment]
Have you run `volk_profile` ?

Can you start your flowgraph in the debugger and make a backtrace? _i.e._ generate `top_block.py` and then run `gdb python` and then in gdb `run top_block.py`. When it crashes you can then get a backtrace using `bt`.

**Comment by hcab14** [comment]
Do you have any news on this issue?

**Comment by williamntv** [comment]
Hello Chris, thank you for reaching out to me. Unfortunately, we were short on time and weren't able to completely resolve the issue. We tried to clean and re-install GNURadio but to no avail. The program kept crashing on us whenever we tried to run it. Yes, my partner did try to debug it and the same message came up saying "segmentation fault". We had to give up and focus on the final exam. Very unfortunate because we came so close to getting it working. We felt that we were not very well equipped with knowledge in Python and programming so we just couldn't pull it off. Anyway, once again, thank you for your support.

**Comment by hooliowobbits** [comment]
Hello, I also had this issue.  I compiled the maint-3.7 branch on ubuntu 18.04 and the packaged version of gnuradio (3.7.11-10).  After reading this i installed `swig3.0` and `doxygen` and completed a clean build again and the reported error went away :)

PS: I however received a different error, and I have logged #5 for that.

**Comment by hcab14** [comment]
> Hello, I also had this issue. I compiled the maint-3.7 branch on ubuntu 18.04 and the packaged version of gnuradio (3.7.11-10). After reading this i installed `swig3.0` and `doxygen` and completed a clean build again and the reported error went away :)
> 
Good to hear that it was helpful.
