### ISSUE TITLE
Could not find a configuration file for package "Gnuradio" that is  compatible with requested version "3.9".

### ISSUE THREAD

**Issue by djacobs010** [hcab14/gr-kiwisdr#4]
Got this error when running cmake ../ from inside the build directory:
```
CMake Error at CMakeLists.txt:76 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.9".

  The following configuration files were considered but not accepted:

    C:/Program Files/GNURadio-3.7/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.7.13.5
```
I have GNURadio version 3.7 installed, which is the requirement listed in the readme, not sure what caused this.  I am also running on Windows, so that could be a factor.

Also, this might be a dumb question, but where is a good place to clone gr-kiwisdr into?

**Comment by hcab14** [comment]
> I have GNURadio version 3.7 installed, which is the requirement listed in the readme, not sure what caused this. I am also running on Windows, so that could be a factor.

The master branch is for GNURadio 3.8 and above. With GNURadio 3.7 use the `maint-3.7` branch.

**Comment by hcab14** [comment]
Closing. Feel free to re-open this issue if the problem you have described persists.
